{
 "title": "Internal Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "substrate_process_start_time_seconds"
    }
   },
   { "name": "metric_namespace", "query": "substrate" }
  ]
 },
 "panels": [
  {
   "title": "Finality Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "substrate_block_height{instance=~\"$Node\", status=\"best\"} - on(instance) substrate_block_height{instance=~\"$Node\", status=\"finalized\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Unfinalized Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "substrate_block_height{instance=~\"$Node\",status=\"best\"} - on (instance) substrate_block_height{instance=~\"$Node\",status=\"finalized\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average block time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(1/rate(substrate_block_height{status=\"best\"}[1m]))/30"
    }
   ]
  },
  {
   "title": "RSS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "memory_usage_rss{exported_instance=~\"$Node\"}",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Unbounded Channels Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(\n  ${metric_namespace}_unbounded_channel_len{instance=~\"${Node}\", action = \"send\"} - ignoring(action) ${metric_namespace}_unbounded_channel_len{instance=~\"${Node}\", action = \"received\"}\n)\n\n# Fallback if the `received` is null\nor on(instance) ${metric_namespace}_unbounded_channel_len{instance=~\"${Node}\", action = \"send\"}",
     "legendFormat": "{{entity}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Unbounded Channels Message Send Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(${metric_namespace}_unbounded_channel_len{instance=~\"${Node}\", action = \"send\"}[$__rate_interval])",
     "legendFormat": "{{entity}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Tasks Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${metric_namespace}_tasks_spawned_total{instance=~\"${Node}\"} - sum(${metric_namespace}_tasks_ended_total{instance=~\"${Node}\"}) without(reason)\n\n# Fallback if tasks_ended_total is null for that task\nor on(instance, task_name) ${metric_namespace}_tasks_spawned_total{instance=~\"${Node}\"}",
     "legendFormat": "{{task_name}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Task Start Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(${metric_namespace}_tasks_spawned_total{instance=~\"${Node}\"}[$__rate_interval])",
     "legendFormat": "{{task_name}} [{{instance}}]"
    }
   ]
  },
  {
   "title": "Sync Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "${metric_namespace}_sync_peers{instance=~\"${Node}\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Dispute Distribution Send Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "increase(polkadot_parachain_dispute_distribution_sent_requests{instance=~\"${Node}\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Dispute Distribution Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "increase(polkadot_parachain_dispute_distribution_received_requests{instance=~\"${Node}\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}